### ISSUE TITLE
how to convey different payloads from the same odmObject

### ISSUE THREAD

**Issue by WAvdBeek** [one-data-model/language#19]
for example
https://oneiota.org/revisions/5299
has a different set of enums for set than retrieve

e.g. how can we model that difference?

**Comment by mjkoster** [comment]
In your example, icemaker status is used as both writeable control (on, off) and readable indicator (on, off, full). I guess full would prevent entering the on state. 

The icemaker control arguably should be modeled as an action, with appropriate constraints on inputData and outputData enums, and the status modeled as a property with its enum including "full". For example, invoking the "on" action on a full icemaker could return "full" as the outputData.

We could conceivable add inputData and outputData to the property definition

**Comment by mjkoster** [comment]
We can also do this with odmView to model interfaces, which is more aligned with OCF

**Comment by asoloway64** [comment]
F2F4: Able to use separate actions.
