### ISSUE TITLE
ReadOnly and WriteOnly

### ISSUE THREAD

**Issue by mjkoster** [one-data-model/language#39]
ReadOnly and WriteOnly might be better expressed as readable and writeable.

We may have had some discussion on this but I think we should have more

readable and writeable seem more natural at constraining data items in the model

they may also be moved to protocol binding, though there is some argument for it being a basic quality of a data item in some models

**Comment by gerickson** [comment]
See related issue https://github.com/one-data-model/language/issues/53.

**Comment by asoloway64** [comment]
F2F4: Agreed that this is a duplicate.
