### ISSUE TITLE
More data types to SDF

### ISSUE THREAD

**Issue by akeranen** [one-data-model/language#5]
OMA/IPSO models are using following data types that do not currently exist in SDF:

* (Unix) Time
* Unsigned integer
* [CoRE link](https://tools.ietf.org/html/rfc6690)
* Opaque

Not currently as a type in IPSO/OMA but likely useful:

* URI / URL

**Comment by akeranen** [comment]
Also need to figure out best practices on what level of detail should be expressed in new types and what should be actually at action/event/property level. For example, "temperature" probably is not a type even if "time" would be.

**Comment by akeranen** [comment]
Currently ODM SDF suggests only "[JSON data types](https://tools.ietf.org/html/rfc8259#section-1)" (string, number, boolean, null, object, array) as possible types for [properties](https://github.com/one-data-model/language/blob/master/sdf.md#odmproperty) et al. Hence there's no way to tell Integer and Float apart, for example. [JSON schema](https://json-schema.org/understanding-json-schema/reference/numeric.html) adds integers to the list.

[SDF examples](https://github.com/mjkoster/ODM-Examples/blob/2e4c8f50fb6b3ab52073be59803adf787a4ac96a/tdl/ipso3300.sdf.json#L130) propose "subtype" keyword to extend from JSON schema capabilities.

The pattern capability helps quite a bit with string types (e.g., URIs and CoRE links).

**Comment by akeranen** [comment]
Related to #24

**Comment by akeranen** [comment]
For Opaque type "byte string" seems to be appropriate name of the type. For example CBOR has that as one of the [major types](https://tools.ietf.org/html/rfc7049#section-2.1).

**Comment by mjkoster** [comment]
odmType vs builtin type  (new keyword) vs. subtype (enum member)

**Comment by akeranen** [comment]
And we probably need something like Object Link too for compact cross-referencing.

**Comment by asoloway64** [comment]
F2F4: All are handled except links which are defined in #76.
